name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {} # permite rodar manualmente

permissions:
  contents: write # <— dá permissão para criar/editar Releases

jobs:
  pack-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci --no-audit --no-fund
      - run: npm run build
      - run: npm pack --pack-destination .

      - name: Create/Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.tgz
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }} # <— usa o token com contents:write
